- name: Setup etcd on sakuracloud
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - network
    - role: etcd
      when: inventory_hostname != "bench"
    - prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.prometheus
      when: inventory_hostname == "bench"
