---
- name: Download and unarchive etcd release
  ansible.builtin.unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v3.5.17/etcd-v3.5.17-linux-amd64.tar.gz
    dest: /usr/bin
    include:
      - etcd-v3.5.17-linux-amd64/etcd
      - etcd-v3.5.17-linux-amd64/etcdctl
      - etcd-v3.5.17-linux-amd64/etcdutl
    list_files: true
    extra_opts:
      - --strip-components=1
    remote_src: true

# https://github.com/etcd-io/etcd/blob/main/contrib/systemd/etcd.service
- name: Set etcd.service
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0600"
    owner: root
    group: root

- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    system: true
    state: present

- name: Create /var/lib/etcd
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    mode: "0700"
    owner: etcd
    group: etcd

- name: Enable now etcd.service
  ansible.builtin.systemd_service:
    name: etcd.service
    state: restarted
    enabled: true
    daemon_reload: true
